# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170306_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
