# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imgLink',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
