# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readerName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('icon', models.CharField(default='img/icons/default.jpeg', max_length=255)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('level', models.IntegerField(default=0)),
                ('registerDate', models.DateTimeField()),
            ],
        ),
    ]
