# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='birthday',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reader',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reader',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
