# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_auto_20170305_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='expNeed',
            field=models.IntegerField(default=10),
        ),
    ]
