# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_reader_expneed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='expNeed',
        ),
        migrations.AddField(
            model_name='reader',
            name='levelRatio',
            field=models.IntegerField(default=0),
        ),
    ]
